### ISSUE TITLE
c.l.c.service.impl.FileServiceImpl       : 文件遍历失败

### ISSUE THREAD

**Issue by mokeeqian** [ALuShu/checksystem#1]
你好啊，我在运行项目时遇到了 “c.l.c.service.impl.FileServiceImpl       : 文件遍历失败”，请问你的文件提交路径是基于什么逻辑的啊？每个教师对应一个文件夹吗？

**Comment by ALuShu** [comment]
啊好久没维护这个了，没想到有人用，是的兄弟，每个教师一个文件夹

**Comment by mokeeqian** [comment]
> 啊好久没维护这个了，没想到有人用，是的兄弟，每个教师一个文件夹

兄弟啊，我在运行你的项目时会遇到上述 错误，是什么原因呢？

**Comment by ALuShu** [comment]
> > 啊好久没维护这个了，没想到有人用，是的兄弟，每个教师一个文件夹
> 
> 兄弟啊，我在运行你的项目时会遇到上述 错误，是什么原因呢？
你好，终于登上来了，这个我项目里只有一个地方打印了，log.info("文件遍历失败", e);，你把后面的异常信息贴出来

**Comment by Emikim1998** [comment]
你好兄弟，可不可以问一下登录页面要怎样才能进入系统呢？猜不到管理员的密码...

**Comment by mokeeqian** [comment]
root root











---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月8日(周六) 中午1:05
收件人: ***@***.***&gt;;
抄送: "Pony ***@***.******@***.***&gt;;
主题: Re: [ALuShu/checksystem] c.l.c.service.impl.FileServiceImpl       : 文件遍历失败 (#1)




 
你好兄弟，可不可以问一下登录页面要怎样才能进入系统呢？猜不到管理员的密码...

**Comment by mokeeqian** [comment]
fixed
